import type { Idea, Collection, Category, Platform } from './types'

// ── Platform metadata ──────────────────────────────────────────
export const platformMeta: Record<Platform, { label: string; color: string; bgClass: string; textClass: string }> = {
  weibo:        { label: '微博',    color: '#E6162D', bgClass: 'bg-red-100 dark:bg-red-900/30',       textClass: 'text-red-600 dark:text-red-400' },
  zhihu:        { label: '知乎',    color: '#0084FF', bgClass: 'bg-blue-100 dark:bg-blue-900/30',     textClass: 'text-blue-600 dark:text-blue-400' },
  v2ex:         { label: 'V2EX',   color: '#333333', bgClass: 'bg-gray-100 dark:bg-gray-800',         textClass: 'text-gray-700 dark:text-gray-300' },
  producthunt:  { label: 'PH',     color: '#DA552F', bgClass: 'bg-orange-100 dark:bg-orange-900/30',  textClass: 'text-orange-600 dark:text-orange-400' },
  reddit:       { label: 'Reddit', color: '#FF4500', bgClass: 'bg-orange-100 dark:bg-orange-900/30',  textClass: 'text-orange-600 dark:text-orange-400' },
  twitter:      { label: 'X',      color: '#1DA1F2', bgClass: 'bg-sky-100 dark:bg-sky-900/30',        textClass: 'text-sky-600 dark:text-sky-400' },
  github:       { label: 'GitHub', color: '#181717', bgClass: 'bg-gray-100 dark:bg-gray-800',         textClass: 'text-gray-700 dark:text-gray-300' },
  hackernews:   { label: 'HN',     color: '#FF6600', bgClass: 'bg-orange-100 dark:bg-orange-900/30',  textClass: 'text-orange-600 dark:text-orange-400' },
  douyin:       { label: '抖音',   color: '#000000', bgClass: 'bg-gray-100 dark:bg-gray-800',         textClass: 'text-gray-700 dark:text-gray-300' },
  xiaohongshu:  { label: '小红书', color: '#FE2C55', bgClass: 'bg-pink-100 dark:bg-pink-900/30',      textClass: 'text-pink-600 dark:text-pink-400' },
}

// ── Categories ─────────────────────────────────────────────────
export const categories: Category[] = ['AI工具', 'SaaS', '消费', '教育', '开发者工具', '设计', '出海', '其他']

// ── Mock Ideas (28 items) ──────────────────────────────────────
export const ideas: Idea[] = [
  // ── Collection: AI写作助手 (c1) ──
  {
    id: 'i1',
    title: '有没有支持长文的AI写作工具，能保持风格一致性？',
    description: '需要写5万字以上的报告，试了几个工具都会在中途风格漂移，希望有能记住全文上下文的AI写作助手。',
    platform: 'zhihu',
    sourceUrl: 'https://www.zhihu.com/question/example1',
    publishedAt: '2025-07-06T10:30:00.000Z',
    heat: 342,
    category: 'AI工具',
    collectionId: 'c1',
  },
  {
    id: 'i2',
    title: 'Seeking an AI writing assistant that handles technical docs',
    description: 'Looking for an AI tool that can maintain consistent formatting and tone across long technical documentation (50+ pages).',
    platform: 'reddit',
    sourceUrl: 'https://www.reddit.com/r/artificial/comments/example2',
    publishedAt: '2025-07-06T08:15:00.000Z',
    heat: 189,
    category: 'AI工具',
    collectionId: 'c1',
  },
  {
    id: 'i3',
    title: '求一个能模仿个人写作风格的AI工具',
    description: '想用AI写公众号文章，但希望它能学习我之前的文章风格，不要每次都像机器写的。',
    platform: 'weibo',
    sourceUrl: 'https://weibo.com/example3',
    publishedAt: '2025-07-05T14:20:00.000Z',
    heat: 256,
    category: 'AI工具',
    collectionId: 'c1',
  },

  // ── Collection: AI代码审查 (c2) ──
  {
    id: 'i4',
    title: '有没有AI代码审查工具能集成到GitHub Actions的？',
    description: '团队想在PR流程里加入AI审查，自动发现潜在bug和代码规范问题，最好能直接评论在PR上。',
    platform: 'v2ex',
    sourceUrl: 'https://www.v2ex.com/t/example4',
    publishedAt: '2025-07-06T09:00:00.000Z',
    heat: 421,
    category: '开发者工具',
    collectionId: 'c2',
  },
  {
    id: 'i5',
    title: 'CodeReview.bot – AI-powered PR reviews on GitHub',
    description: 'Just launched on Product Hunt! An AI tool that reviews your PRs automatically, catches bugs before humans do.',
    platform: 'producthunt',
    sourceUrl: 'https://www.producthunt.com/posts/example5',
    publishedAt: '2025-07-06T03:00:00.000Z',
    heat: 567,
    category: '开发者工具',
    collectionId: 'c2',
  },
  {
    id: 'i6',
    title: 'AI Code Review tools comparison: CodeRabbit vs Cursor vs Copilot',
    description: 'Has anyone done a thorough comparison? Looking for something that goes beyond linting.',
    platform: 'hackernews',
    sourceUrl: 'https://news.ycombinator.com/item?id=example6',
    publishedAt: '2025-07-05T22:30:00.000Z',
    heat: 312,
    category: '开发者工具',
    collectionId: 'c2',
  },

  // ── Collection: AI客服 (c3) ──
  {
    id: 'i7',
    title: '中小企业用的AI客服系统，求推荐',
    description: '公司客服团队只有5个人，每天处理300+咨询，想用AI分流常见问题，人工处理复杂的。',
    platform: 'zhihu',
    sourceUrl: 'https://www.zhihu.com/question/example7',
    publishedAt: '2025-07-06T07:45:00.000Z',
    heat: 198,
    category: 'AI工具',
    collectionId: 'c3',
  },
  {
    id: 'i8',
    title: 'Built an AI customer support agent that resolves 60% of tickets autonomously',
    description: 'We trained a LLM on our support history and deployed it as a first-line responder. Sharing our architecture and results.',
    platform: 'twitter',
    sourceUrl: 'https://twitter.com/example8',
    publishedAt: '2025-07-05T16:00:00.000Z',
    heat: 445,
    category: 'AI工具',
    collectionId: 'c3',
  },
  {
    id: 'i9',
    title: '有没有支持多语言的AI客服？需要覆盖东南亚市场',
    description: '业务扩展到东南亚，需要泰语、越南语、印尼语的AI客服，找了几个工具都不支持。',
    platform: 'weibo',
    sourceUrl: 'https://weibo.com/example9',
    publishedAt: '2025-07-04T11:30:00.000Z',
    heat: 134,
    category: 'AI工具',
    collectionId: 'c3',
  },

  // ── Collection: SaaS订阅管理 (c4) ──
  {
    id: 'i10',
    title: 'SaaS订阅太多管理不过来，有没有统一管理工具？',
    description: '公司用了30+个SaaS，续费时间分散，经常漏掉导致服务中断。需要一个能集中管理和提醒的工具。',
    platform: 'v2ex',
    sourceUrl: 'https://www.v2ex.com/t/example10',
    publishedAt: '2025-07-06T06:00:00.000Z',
    heat: 287,
    category: 'SaaS',
    collectionId: 'c4',
  },
  {
    id: 'i11',
    title: 'Show HN: I built a SaaS spend tracker that saved us $12k/year',
    description: 'Found unused subscriptions and duplicate tools. Open-sourced the detection logic.',
    platform: 'hackernews',
    sourceUrl: 'https://news.ycombinator.com/item?id=example11',
    publishedAt: '2025-07-05T19:00:00.000Z',
    heat: 523,
    category: 'SaaS',
    collectionId: 'c4',
  },
  {
    id: 'i12',
    title: 'SaaS subscription fatigue is real – anyone else feeling it?',
    description: 'Between Notion, Figma, Linear, Vercel, Stripe... the bills add up. Looking for alternatives or bundle deals.',
    platform: 'reddit',
    sourceUrl: 'https://www.reddit.com/r/SaaS/comments/example12',
    publishedAt: '2025-07-04T15:45:00.000Z',
    heat: 167,
    category: 'SaaS',
    collectionId: 'c4',
  },

  // ── Collection: AI教育/学习 (c5) ──
  {
    id: 'i13',
    title: '有没有AI辅助学习的工具，能根据错题生成类似题目？',
    description: '孩子上初中，数学错题本想用AI管理，自动生成同类题目巩固练习。',
    platform: 'xiaohongshu',
    sourceUrl: 'https://www.xiaohongshu.com/example13',
    publishedAt: '2025-07-06T05:30:00.000Z',
    heat: 389,
    category: '教育',
    collectionId: 'c5',
  },
  {
    id: 'i14',
    title: 'AI tutors that actually adapt to learning style?',
    description: 'Most AI tutoring tools just dump information. Looking for ones that adjust teaching method based on student response patterns.',
    platform: 'reddit',
    sourceUrl: 'https://www.reddit.com/r/edtech/comments/example14',
    publishedAt: '2025-07-05T12:00:00.000Z',
    heat: 234,
    category: '教育',
    collectionId: 'c5',
  },
  {
    id: 'i15',
    title: '求推荐AI编程学习平台，带交互式代码练习的那种',
    description: '零基础学Python，希望有AI老师能实时纠正代码错误，比看视频效率高。',
    platform: 'zhihu',
    sourceUrl: 'https://www.zhihu.com/question/example15',
    publishedAt: '2025-07-04T09:00:00.000Z',
    heat: 312,
    category: '教育',
    collectionId: 'c5',
  },

  // ── Collection: 无代码/低代码 (c6) ──
  {
    id: 'i16',
    title: '有没有适合非技术人员搭建内部工具的无代码平台？',
    description: '运营团队需要搭建各种数据看板和审批流程，开发资源不够，想找好用的无代码工具。',
    platform: 'v2ex',
    sourceUrl: 'https://www.v2ex.com/t/example16',
    publishedAt: '2025-07-06T04:00:00.000Z',
    heat: 198,
    category: 'SaaS',
    collectionId: 'c6',
  },
  {
    id: 'i17',
    title: 'Retool vs Appsmith vs Budibase – which internal tool builder?',
    description: 'Need to build CRUD apps quickly with SSO. Comparing the top 3 open-source/low-code options.',
    platform: 'hackernews',
    sourceUrl: 'https://news.ycombinator.com/item?id=example17',
    publishedAt: '2025-07-05T18:00:00.000Z',
    heat: 267,
    category: 'SaaS',
    collectionId: 'c6',
  },

  // ── Collection: 出海工具 (c7) ──
  {
    id: 'i18',
    title: '独立开发者出海，收款用什么方案最省心？',
    description: '做了一个Chrome插件想全球收费，Stripe太重，Lemon Squeezy和Paddle哪个好？',
    platform: 'v2ex',
    sourceUrl: 'https://www.v2ex.com/t/example18',
    publishedAt: '2025-07-06T03:30:00.000Z',
    heat: 456,
    category: '出海',
    collectionId: 'c7',
  },
  {
    id: 'i19',
    title: 'Going global as a solo dev – payment, tax, and compliance checklist',
    description: 'Compiled everything I learned launching in 15+ countries. The hardest part was tax compliance, not payments.',
    platform: 'twitter',
    sourceUrl: 'https://twitter.com/example19',
    publishedAt: '2025-07-05T20:00:00.000Z',
    heat: 678,
    category: '出海',
    collectionId: 'c7',
  },
  {
    id: 'i20',
    title: '出海产品怎么做多语言SEO？',
    description: '英文站做了但Google排名上不去，有没有AI辅助生成多语言SEO内容的工具？',
    platform: 'weibo',
    sourceUrl: 'https://weibo.com/example20',
    publishedAt: '2025-07-04T14:00:00.000Z',
    heat: 234,
    category: '出海',
    collectionId: 'c7',
  },

  // ── Collection: AI设计工具 (c8) ──
  {
    id: 'i21',
    title: '有没有AI生成UI设计稿的工具？从需求描述直接出设计',
    description: '产品经理写完PRD后，希望能直接生成高保真设计稿，设计师只需要微调。',
    platform: 'xiaohongshu',
    sourceUrl: 'https://www.xiaohongshu.com/example21',
    publishedAt: '2025-07-06T02:00:00.000Z',
    heat: 345,
    category: '设计',
    collectionId: 'c8',
  },
  {
    id: 'i22',
    title: 'v0.dev vs Galileo AI vs Uizard – AI UI generators compared',
    description: 'Tested all three for generating React components from text prompts. Results were surprising.',
    platform: 'producthunt',
    sourceUrl: 'https://www.producthunt.com/posts/example22',
    publishedAt: '2025-07-05T17:00:00.000Z',
    heat: 412,
    category: '设计',
    collectionId: 'c8',
  },

  // ── Standalone ideas ──
  {
    id: 'i23',
    title: '有没有能自动生成API文档的工具？支持TypeScript',
    description: '后端API经常变更，手动维护文档太痛苦，希望有工具能从代码自动生成并更新文档。',
    platform: 'github',
    sourceUrl: 'https://github.com/example23',
    publishedAt: '2025-07-06T01:00:00.000Z',
    heat: 156,
    category: '开发者工具',
  },
  {
    id: 'i24',
    title: '想找一个能管理多个社交平台内容的工具',
    description: '同时运营微博、小红书、抖音，需要一个统一的内容管理和发布工具，最好能AI辅助生成不同平台的文案。',
    platform: 'weibo',
    sourceUrl: 'https://weibo.com/example24',
    publishedAt: '2025-07-05T13:00:00.000Z',
    heat: 278,
    category: '消费',
  },
  {
    id: 'i25',
    title: 'Need a lightweight analytics tool for solo founders',
    description: 'GA4 is overkill. Looking for privacy-friendly, simple analytics that shows me what matters: traffic, sources, conversions.',
    platform: 'producthunt',
    sourceUrl: 'https://www.producthunt.com/posts/example25',
    publishedAt: '2025-07-05T10:00:00.000Z',
    heat: 334,
    category: 'SaaS',
  },
  {
    id: 'i26',
    title: '有没有AI辅助的健康管理app？能分析体检报告给建议',
    description: '每年体检报告看不懂，希望有AI能解读体检数据并给出个性化的健康建议。',
    platform: 'zhihu',
    sourceUrl: 'https://www.zhihu.com/question/example26',
    publishedAt: '2025-07-04T16:00:00.000Z',
    heat: 423,
    category: '消费',
  },
  {
    id: 'i27',
    title: 'Show HN: Open-source alternative to Notion with end-to-end encryption',
    description: 'Built this because I wanted my notes encrypted by default. Self-hostable, supports collaboration.',
    platform: 'hackernews',
    sourceUrl: 'https://news.ycombinator.com/item?id=example27',
    publishedAt: '2025-07-04T08:00:00.000Z',
    heat: 389,
    category: '开发者工具',
  },
  {
    id: 'i28',
    title: '有没有支持团队协作的AI脑图工具？',
    description: '团队头脑风暴时希望能实时协作画脑图，并且AI能根据已有节点扩展新想法。',
    platform: 'douyin',
    sourceUrl: 'https://www.douyin.com/example28',
    publishedAt: '2025-07-03T15:00:00.000Z',
    heat: 167,
    category: '设计',
  },
]

// ── Mock Collections (8 items) ─────────────────────────────────
export const collections: Collection[] = [
  {
    id: 'c1',
    title: 'AI写作助手需求升温',
    summary: '多个平台用户表达了对长文风格一致、个人风格模仿的AI写作工具的强烈需求。现有工具在长文本上下文保持和个人风格学习方面仍有明显短板。',
    category: 'AI工具',
    ideaIds: ['i1', 'i2', 'i3'],
    createdAt: '2025-07-06T11:00:00.000Z',
  },
  {
    id: 'c2',
    title: 'AI代码审查成为开发团队刚需',
    summary: '从V2EX到Hacker News，开发者社区对AI辅助代码审查的讨论热度持续走高。核心诉求是深度集成CI/CD流程，超越简单lint，提供真正的bug发现能力。',
    category: '开发者工具',
    ideaIds: ['i4', 'i5', 'i6'],
    createdAt: '2025-07-06T09:30:00.000Z',
  },
  {
    id: 'c3',
    title: 'AI客服落地的真实痛点',
    summary: '中小企业需要低成本的AI客服方案，多语言支持（尤其东南亚市场）是未被满足的需求。有人已实现60%工单自动解决，但可复制性存疑。',
    category: 'AI工具',
    ideaIds: ['i7', 'i8', 'i9'],
    createdAt: '2025-07-06T08:00:00.000Z',
  },
  {
    id: 'c4',
    title: 'SaaS订阅管理：从痛点到创业机会',
    summary: 'SaaS工具泛滥导致订阅管理成为普遍痛点。有人通过管理工具年省$12k，说明这个方向既有需求也有付费意愿。',
    category: 'SaaS',
    ideaIds: ['i10', 'i11', 'i12'],
    createdAt: '2025-07-06T06:30:00.000Z',
  },
  {
    id: 'c5',
    title: 'AI+教育的个性化学习需求',
    summary: '从错题本到编程学习，用户希望AI能提供个性化的学习体验。关键差异点在于"自适应教学"而非简单的"AI问答"。',
    category: '教育',
    ideaIds: ['i13', 'i14', 'i15'],
    createdAt: '2025-07-06T05:00:00.000Z',
  },
  {
    id: 'c6',
    title: '无代码/低代码：非技术人员的造物需求',
    summary: '运营和产品团队希望自主搭建内部工具，降低对开发资源的依赖。Retool类工具的对比讨论说明市场已进入选型深水区。',
    category: 'SaaS',
    ideaIds: ['i16', 'i17'],
    createdAt: '2025-07-06T04:30:00.000Z',
  },
  {
    id: 'c7',
    title: '独立开发者出海的全链路需求',
    summary: '从收款合规到多语言SEO，出海创业者面临一系列实际问题。有经验的开发者分享的全链路清单获得高关注度，说明信息差仍然巨大。',
    category: '出海',
    ideaIds: ['i18', 'i19', 'i20'],
    createdAt: '2025-07-06T03:30:00.000Z',
  },
  {
    id: 'c8',
    title: 'AI生成UI设计稿：从文字到界面的跨越',
    summary: '产品经理和设计师都在关注AI UI生成工具，v0.dev等产品已获得实际验证。核心价值在于减少从需求到设计的转译成本。',
    category: '设计',
    ideaIds: ['i21', 'i22'],
    createdAt: '2025-07-06T02:30:00.000Z',
  },
]
